**** Starting postgresql sql queries execution ****
Traceback (most recent call last):
  File "db_utilities.py", line 169, in <module>
    checkCountpostgresql()
  File "db_utilities.py", line 15, in checkCountpostgresql
    "host": sys.argv[4],
IndexError: list index out of range
something went wrong in script execution
